

export enum AlarmChangeNotificationReason$v1 {
  unknown = 'Unknown',
  attachment = 'Attachment',
  title = 'Title',
  priority = 'Priority',
  reportedTime = 'ReportedTime',
  location = 'Location',
  keyword = 'Keyword',
  isManaged = 'IsManaged',
  remark = 'Remark',
  property = 'Property',
  created = 'Created',
  deleted = 'Deleted',
  industry = 'Industry',
  type = 'Type',
  primaryContact = 'PrimaryContact',
  hyperlink = 'Hyperlink'
}

export class AlarmChangeNotification$v1 {
  /** Alarm id */
  id?: string;

  /** The reason for the notification */
  reason?: AlarmChangeNotificationReason$v1;

  /** Id of the tenant the alarm is for */
  tenantId?: string;

  /** The time the notification was created */
  timestamp?: Date;

  /** Unique identify for this notification generated by the system at creation  */
  systemCorrelationId?: string;

  constructor(param: AlarmChangeNotification$v1 = {} as AlarmChangeNotification$v1) {
    const {
      id = null,
      reason = AlarmChangeNotificationReason$v1.unknown,
      tenantId = null,
      timestamp = null,
      systemCorrelationId = null
    } = param;

    this.id = id;
    this.reason = reason;
    this.tenantId = tenantId;
    this.timestamp = timestamp;
    this.systemCorrelationId = systemCorrelationId;
  }
}
