/**
 * Identifiers of the different change reasons
 */
export enum PipelineChangeReason$v1 {
    Unknown = 'Unknown',
    BackupStarted = 'BackupStarted',
    BackupComplete = 'BackupComplete',
    BackupCompleteWithErrors = 'BackupCompleteWithErrors',
    RestoreStarted = 'RestoreStarted',
    RestoreComplete = 'RestoreComplete',
    RestoreCompleteWithErrors = 'RestoreCompleteWithErrors',
    DeleteStarted = 'DeleteStarted',
    DeleteComplete = 'DeleteComplete',
    GeneratingDownload = 'GeneratingDownload',
    DownloadReady = 'DownloadReady',
    DownloadFailed = 'DownloadFailed',
    DeleteBackupStarted = 'DeleteBackupStarted',
    DeleteBackupComplete = 'DeleteBackupComplete',
    PipelineFailure = 'PipelineFailure',
    PipelineCancelled = 'PipielineCancelled',
    PipelineNotFoundFailure = 'PipelineNotFoundFailure',
    PipelineUpdated = 'PipelineUpdated'
}

/**
 * An object that represents a change notification
 */
export class PipelineChangeNotifications$v1 {
    /**
     * Same for all messages that come from this source
     */
    name?: string;

    /**
     * The reason for the notification
     */
    reason?: PipelineChangeReason$v1;

    /**
     * Pipeline id
     */
    runId?: string;

    /**
     * Pipeline id of the parent if exists
     */
    parentPipeline?: string;

    /**
     * Pipeline tenant id
     */
    tenantId?: string;

    /**
     * Timestamp at pipeline start
     */
    startTime?: Date;

    /**
     * TImestamp at pipeline end
     */
    endTime?: Date;

    /**
     * Timestamp of last modified
     */
    lastModifiedTime?: Date;

    /**
     * Timestamp of change notification creation
     */
    timestamp?: Date;

    /**
     * Unique Identify for this notification generated by the system at creation
     */
    systemCorrelationId?: string;

    /**
     * The current runtime duration of the pipeline
     */
    runTime?: string;
}
