export enum MapLayerOptionName {
    Attribution = 'attribution',
    AutoRefresh = 'autoRefresh',
    AutoRefreshInterval = 'autoRefreshInterval',
    CRS = 'crs',
    EnableFeatInfo = 'enableFeatInfo',
    FeatInfoFormat = 'featInfoFormat',
    Format = 'format',
    HXDRLayerId = 'hxdrLayerId',
    LocalAccessOnly = 'localAccessOnly',
    MaxFeatures = 'maxFeatures',
    Subdomains = 'subdomains',
    TileLevels = 'tileLevels',
    TileMatrixSetId = 'tileMatrixSetId',
    TileSize = 'tileSize',
    TMS = 'tms',
    Transparent = 'transparent',
    VectorStyleProps = 'vectorStyleProps',
    Version = 'version',
    WFSOutputFormat = 'wfsOutputFormat',
    WMTSLayerId = 'wmtsLayerId',
    WorkingLayer = 'workingLayer',
    ZoomOffset = 'zoomOffset'
}