/* eslint-disable */
import { ChangeOperationDtoV1 } from "./change-operation-dto-v1";

/*  DO NOT EDIT ANY .TS FILES WITH THIS COMMENT
    THESE .TS FILES ARE GENERATED BY A CORRESPONDING .CS FILE AND A .TST FILE
    BY USING THE TYPEWRITER EXTENSION:
    https://frhagn.github.io/Typewriter */

export class ChangeRecordDtoV1<T> {
    public user: string = null;
    public timestamp: string = null;
    public value: T;
    public operation: ChangeOperationDtoV1;
}
