/* eslint-disable */
/*  DO NOT EDIT ANY .TS FILES WITH THIS COMMENT
    THESE .TS FILES ARE GENERATED BY A CORRESPONDING .CS FILE AND A .TST FILE
    BY USING THE TYPEWRITER EXTENSION:
    https://frhagn.github.io/Typewriter */

export class BaseResultResponse {
    public result: any = null;
    public messages: string[] = [];
    public statusCode: number = 0;
}
