/* eslint-disable */
/*  DO NOT EDIT ANY .TS FILES WITH THIS COMMENT
    THESE .TS FILES ARE GENERATED BY A CORRESPONDING .CS FILE AND A .TST FILE
    BY USING THE TYPEWRITER EXTENSION:
    https://frhagn.github.io/Typewriter */

export class BaseErrorResponse {
    public errors: string[] = [];
    public errorId: string = null;
    public statusCode: number = 0;
}
